[font]
size = 13.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"

[general]
import = ["~/.config/alacritty/themes/duskfox.toml"]

[keyboard]
bindings = [
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Command", chars = "\u001BOH" },
    { key = "Right", mods = "Command", chars = "\u001BOF" },
]

[window.dimensions]
columns = 150
lines = 65

[window]
padding.x = 25
padding.y = 25
decorations = "buttonless"
# opacity = 0.975
